version: '2'
services:
  app:
    image: "nebo15/annon.web"
    links:
      - "api:api"
    depends_on:
      - api
    environment:
      - MANAGEMENT_ENDPOINT=http://api:4001
      - PUBLIC_ENDPOINT=http://api:4000
    ports:
      - "8080:8080"
  api:
    restart: "always"
    image: "nebo15/annon_api:latest"
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
    environment:
      - DB_NAME=annon
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - GATEWAY_PUBLIC_PORT=4000
      - GATEWAY_MANAGEMENT_PORT=4001
      - GATEWAY_PRIVATE_PORT=4002
      - ERLANG_COOKIE=c2VjcmV0X2VybGFuZ19jb29raWUK
      - LISTEN_DIST_MIN=10000
      - LISTEN_DIST_MAX=10100
      - APP_MIGRATE=true
      - POD_IP=127.0.0.1
      - SKYCLUSTER_STRATEGY=Cluster.Strategy.Epmd
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
  postgres:
    image: "nebo15/alpine-postgre:9.6.2"
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=annon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # volumes:
    #   - '.postgres:/var/lib/postgresql/data'
